// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIlXpy7cJ7nnw60Jtz3IRx5NBxs9RF0UA',
    appId: '1:1011622029564:web:a207ba2987725f25f90f79',
    messagingSenderId: '1011622029564',
    projectId: 'cebuarena-e378a',
    authDomain: 'cebuarena-e378a.firebaseapp.com',
    storageBucket: 'cebuarena-e378a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4szylUuZRakcQQYspHphSFSIy9M4L88',
    appId: '1:1011622029564:android:fdd88cd2996957c1f90f79',
    messagingSenderId: '1011622029564',
    projectId: 'cebuarena-e378a',
    storageBucket: 'cebuarena-e378a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssKlTRdu8Kt4KETljla4HxG1bIj5jMG0',
    appId: '1:1011622029564:ios:3e3f4f33105f8801f90f79',
    messagingSenderId: '1011622029564',
    projectId: 'cebuarena-e378a',
    storageBucket: 'cebuarena-e378a.appspot.com',
    iosClientId: '1011622029564-vp721eki1dm146769914h8m9f085hmb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.captsoneUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDssKlTRdu8Kt4KETljla4HxG1bIj5jMG0',
    appId: '1:1011622029564:ios:e25a38cc9966a9def90f79',
    messagingSenderId: '1011622029564',
    projectId: 'cebuarena-e378a',
    storageBucket: 'cebuarena-e378a.appspot.com',
    iosClientId: '1011622029564-96o7q6ljsp64hjdqfqnfpgbc4k7pjc03.apps.googleusercontent.com',
    iosBundleId: 'com.example.captsoneUi.RunnerTests',
  );
}
